title = "Tater Joe’s Old-Time Musical Mercantile"
description = "Transcriptions of 675+ fiddle tunes, clawhammer banjo tabs for over 600 tunes, and backup guitar chords for many of the tunes. MIDI files of the melody line also available for many of the tunes. Tunes are organized by the key in which the tune is intended to be played and listed alphabetically. Clean, modern website with fast-loading resources."
author = "Ken Torke"
url = "http://taterjoes.com/"
