title = "Mainly Norfolk : Bibliography"
description = "Selection of classic and contemporary volumes concerning English and Scottish traditional music, with a few selections related to the British folk revival."
author = "Reinhard Zierke"
url = "https://mainlynorfolk.info/folk/books"
