title = "Prolegomena to a Study of the Principal Melodic Families of British-American Folk Song"
description = "Journal of American Folklore 63, no. 247 (1950), pp 1–44. Theoretical consideration of variation and shared features among “tune families” as perceived by an experienced collector of folk melodies."
author = "Samuel P. Bayard"
url = "https://www.jstor.org/stable/537347"
