title = "Early Child Ballads"
description = "Article exploring what is known about sources for Child ballads before 1600, considering how historical perspective can inform attempts at period performance."
author = "Dani Zweig"
url = "http://www.pbm.com/~lindahl/ballads/early_child/"
