extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  node: true

plugins:
  - import

rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: [ test/*.js ]
  import/extensions:
    - error
    - always
    - ignorePackages: true
