title = "List of blackface minstrel songs"
description = "As described: “This is a list of songs that either originated in blackface minstrelsy or are otherwise closely associated with that tradition. Songwriters and publication dates are given where known.”"
author = "Wikipedia contributors"
url = "https://en.wikipedia.org/wiki/List_of_blackface_minstrel_songs"
