title = "List of pre-1920 jazz standards"
description = "Early country and blues performers were influenced by the popular music of the day and often reinterpreted the styles and themes of popular songs in their own repertoires. This list of early 20th-century standards provides insight into what dance bands were playing and what radio and phonograph listeners were hearing in this era. See also Wikipedia’s lists of standards for the 1920s and 30s."
author = "Wikipedia contributors"
url = "https://en.wikipedia.org/wiki/List_of_pre-1920_jazz_standards"
