title = "The American Folk Song Collection"
description = "As described: “The collection contains folk songs representing most of the geographic and cultural populations of the United States. Each song has been selected for its beauty, suitability for teaching and musical versatility. All songs in the collection include lyrics, a musical score and song analysis showing how it can be used to develop children’s musical and cultural understanding.”"
author = "Kodály Center (Holy Names University)"
url = "http://kodaly.hnu.edu/collection.cfm"
