title = "Scales and Modes in Scottish Traditional Music"
description = "Incredibly useful primer in the theory of modes as it applies to Scottish traditional music, and by extension to other European and non-European folk idioms. Includes many tune examples in ABC notation."
author = "Jack Campin"
url = "http://www.campin.me.uk/Music/Modes/"
