title = "Early Music Muse : Index of articles"
description = "Blog posts reflecting original research and synthesis by a musician and singer who plays Medieval/Renaissance music on period instruments and traditional/folk music on guitar. See in particular the category “traditional/folk music and early music” and the post “Performing medieval music. Part 3: The medieval style.”"
author = "Ian Pittaway"
url = "https://earlymusicmuse.com/emm-blog-index/"
