title = "The Banjo"
description = "Provides historical context and contemporary insights to answer the question of why the banjo has long been associated with African-American culture but few African-American banjo players can be found in recorded music."
author = "Jim Crow Museum of Racist Memorabilia (Ferris State University, Michigan)"
url = "https://www.ferris.edu/HTMLS/news/jimcrow/question/2020/may.htm"
