title = "\"Here of a Sunday Morning\": The Research Periods"
description = "Introduction to early Western art music organized by research periods. Created by the host of the program \"Here of a Sunday Morning\" on WBAI 99.5 in New York."
author = "Chris Whent"
url = "http://www.hoasm.org/periods.html"
