title = "Early Music Frequently Asked Questions : Site outline"
description = "A large collection of notes compiled over the a 25-year period summarizing original synthesis of scholarship on early Western art music. See in particular the sections on music theory and Pythagorian tuning under “Chord Structure in Medieval Music.”"
author = "Todd M. McComb"
url = "http://www.medieval.org/emfaq/site.html"
