title = "Musical Traditions Internet Magazine: Articles"
description = "An assortment of articles on obscure but interesting topics related to traditional/folk music from the British Isles, North America, and beyond."
author = "Rod Stradling"
url = "http://www.mustrad.org.uk/arts_abc.htm"
