title = "A Beginner's Guide to Modal Harmony"
description = "Excellent introductory article on the use of modal harmony in Western music prior to the Classical era. Two tables showing Renaissance modes (first with white keys only, then from C starting pitch) are particularly helpful."
author = "Michael Robinson and Vicki Parrish"
url = "http://www.standingstones.com/modeharm.html"
