title = "Tonal harmony vs. modal harmony"
description = "Introduces the distinction between tonal/functional and modal theories of harmony from the perspective of jazz accompaniment. Useful for thinking about chording and bass lines in traditional/folk music."
author = "Walk That Bass"
url = "http://www.thejazzpianosite.com/jazz-piano-lessons/modern-jazz-theory/tonal-harmony-vs-modal-harmony/"
