title = "WeenieCampbell.com : Wiki : Musicianship : Guitar"
description = "Approximation of guitar tuning and pitch (tonal center) used by influential performers in early country and blues recordings of the 1920s and 30s, with additional performance notes for each artist."
author = "Weenie Campbell and contributors"
url = "https://weeniecampbell.com/wiki/index.php?title=Category:Guitar"
lastUpdated = "2019"
