title = "Hank Williams: A Comprehensive Discography"
description = "Attempts to sort out a recording history muddled by undated sessions and overdubbed posthumous releases. Also includes discographies for The Carter Family, Johnny Cash, and Kitty Wells."
author = "Mike Taylor"
url = "https://www.hankwilliamsdiscography.com/index.php"
