title = "Afro-Atlantic Music as Archive"
description = "Paper for Africa N’Ko: La bibliothèque coloniale en débat. As described: “[The paper] explores how thinkers including W.E.B. DuBois and Paul Gilroy have thought about the history of music. The second half of the paper uses the example of the banjo to suggest ways in which a combination of textual, material, and visual analysis can allow us to piece together fragments into a larger history of music.”"
author = "Laurent Dubois"
url = "https://sites.duke.edu/banjology/files/2013/03/Dubois-Afro-Atlantic-Music.docx"
