title = "“Our Singing Country”: John and Alan Lomax, Leadbelly, and the Construction of an American Past."
description = "Published in American Quarterly 43 (Dec 1991), pp. 602–24."
author = "Benjamin Filene"
url = "http://libres.uncg.edu/ir/uncg/f/B_Filene_Our_1991.pdf"
