title = "The Social Agenda of Stephen Foster’s Plantation Melodies"
description = "Examines competing narratives about Stephen Foster’s racial attitudes and their expression in his popular songs."
author = "Steven Saunders"
url = "https://www.jstor.org/stable/10.5406/americanmusic.30.3.0275"
