title = "Berea Sound Archives"
description = "As described: “Berea's non-commercial audio and video collections document Appalachian history and culture, and the history of Berea College. . . . These collections include field recordings from homes and churches, local and regional folk festivals, student performances, presentations of notable scholars, preachers, and social activists who have visited Berea.”"
author = "Berea College (Kentucky)"
url = "https://soundarchives.berea.edu/"
