title = "Published Recordings from the American Folklife Center"
description = "Four long-playing albums produced from field recordings made between 1934 and 1952, available as streaming audio."
author = "American Folklife Center, Library of Congress"
url = "https://www.loc.gov/search/?fa=partof:published+recordings+from+the+american+folklife+center"
