title = "Slippery-Hill"
description = "Streaming audio of fiddlers playing old-time tunes from field recordings, festivals, and other non-commercial sources. Includes Appalachian fiddlers and some from other parts of the US and Canada. Recordings are searchable and indexed by title, artist, tuning, key, and collection (with several collections corresponding to published tune books)."
author = "Larry Warren"
url = "https://www.slippery-hill.com/search-page"
