title = "The Online Discographical Project"
description = "Extensive catalog of 78-RPM releases indexed by record company, label, and series, with matrix numbers and additional recording data where available. A good source for information about “hillbilly” and “race” series not yet indexed by DAHR."
author = "Steven Abrams"
url = "http://78discography.com/"