title = "The Field Recorders’ Collective"
description = "Albums of recorded music by old-time performers, many from Appalachia and Southern states. Available for purchase or to preview as lo-fi streaming audio."
url = "https://fieldrecorder.bandcamp.com/"
