title = "British Library: World and Traditional Music"
description = "Includes field recordings from the British Isles as well as historical and ethnomusicological collections from other parts of the world."
author = "The British Library"
url = "https://sounds.bl.uk/World-and-traditional-music/"
