title = "African American Sheet Music"
description = "As described: \"consists of music by and relating to African Americans, from the 1820s to the present day.\" The digitized collection contains 1455 items. Most of the digitized sheet music appears to be derogatory Minstrel and \"Coon\" material (probably because later material by African-American composers is still under copyright). However, W.C. Handy's popular blues arrangements can also be found in this collection."
author = "Brown University Library"
url = "https://repository.library.brown.edu/studio/collections/id_555/"
