title = "Banjology"
description = "Explores the history of the banjo and its African-American roots through a selection of audio and textual materials. See in particular the comparative analysis of six historical field recordings of the banjo tune known as “The Coo Coo Bird.” As indicated: “The website was originally created as the basis for events taking place at Tulane University on April 21-22, 2013 around the theme of ‘The Banjo and the African Diaspora.’”"
author = "Laurent Dubois (Duke University), David K. Garner, and Mary Caton Lingold"
url = "https://sites.duke.edu/banjology/"
