title = "Scottish Lute Recording Project"
description = "Streaming audio of recordings based on lute tablature found in five manuscripts from 17th century Scotland."
author = "Rob MacKillop"
url = "https://scottishlute.com"
