title = "Troubadour Melodies Database"
description = "As described: \"This site contains transcriptions for the extant troubadour melodies. Each melody appears as it is found in its manuscript, including all of the melodies for each text. The database will be fully searchable for notes, note patterns, and will also allow searches by contour on the Melody Search page.\" Part of a dissertation project entitled, \"Digital Approaches to Troubadour Song.\""
author = "Katie Chapman"
url = "http://www.troubadourmelodies.org/"
