title = "Samuel Preston Bayard Folklore Recordings"
description = "Field recordings of songs and tunes by old-timers in Southwestern Pennsylvania made between 1948 and 1962."
author = "Penn State University Special Collections Library"
url = "https://www.youtube.com/playlist?list=PLfkrWr_vIGB9l33oOjTC2M6JlhxfoPlQz"
