title = "The Online Books Page : Folk Songs, English"
description = "This site indexes books that are out of copyright and are free to access and download in electronic form. The link points to the subject index for “Folk Songs, English.” See nearby and related indexes as well."
author = "John Mark Ockerbloom (University of Pennsylvania)"
url = "https://onlinebooks.library.upenn.edu/webbin/book/browse?type=lcsubc&key=Folk%20songs%2c%20English&c=x"
