title = "List of the Child Ballads"
description = "This Wikipedia page is a listing with concise summaries of the 305 English and Scottish ballads catalogued by Francis James Child in the latter part of the 19th century. Links are provided to individual Wikipedia entries for many of the ballads."
author = "Wikpedia contributors"
url = "https://en.wikipedia.org/wiki/List_of_the_Child_Ballads"
