type Resource {
  slug: String! @unique
  url: String! @unique
  title: String!
  author: String!
  description: String!
  category: Category!
  tags: [Tag!] @relation
}

type Category {
  slug: String! @unique
  resources: [Resource!]
}

type Tag {
  slug: String! @unique
  resources: [Resource!] @relation
}

type Query {
  allCategories: [Category!]
  allTags: [Tag!]
  allResources: [Resource!]
  findCategoryBySlug(slug: String!): Category
  findTagBySlug(slug: String!): Tag
  findResourceBySlug(slug: String!): Resource
  findResourceByUrl(url: String!): Url
}

type Mutation {
  deleteCategoryBySlug(slug: String!): Category
  deleteTagBySlug(slug: String!): Tag
  deleteResourceBySlug(slug: String!): Resource
}
