title = "The Way of the Fiddle: One Fiddler's Collection of Old-Time Tunes"
description = "As described: “This is a collection of old-time fiddle tunes — most of them from Appalachia — that I collected for my own use and would like to share with other fiddlers who love this kind music.” Includes 58 tunes with links to PDF files with standard music notation. Fast static HTML website."
author = "John Brady"
url = "http://www.abbamoses.com/fiddledo/fiddlepage.html"
