title = "Tune Collections on the Internet"
description = "An index of sites with freely available music notation for dance tunes and folk instrumentals from various regions of Europe, North American, and Australia. Identifies which sites have sheet music in image/PDF formats and which have ABC notation. A few of the links may be outdated, but the site is actively maintained as of 2020. This is a great resource for finding obscure or unfamiliar folk material on sites you wouldn't otherwise come across."
author = "Mickey Koth"
url = "https://www.biteyourownelbow.com/webtunes.htm"
