title = "Session Tunebooks"
description = "Repository of session tune collections published on other sites, with a focus on Irish and Scottish tunes. Includes some digital files that have been circulating on the web since the 90s, some more recent compilations, and some scans of out-of-print books as well. Links to sites with ABC notation where available."
author = "Pete Braccio"
url = "http://www.braccio.me/session.html"
