title = "Jack Campin’s Homepage"
description = "Transcriptions of traditional Scottish music (and some other ethnic folk musics) from various sources, including some from the 18th century and older. Links point to text files formatted in ABC notation. Fast static HTML website."
author = "Jack Campin"
url = "http://www.campin.me.uk/"
