title = "Old Time Fiddle Tunes"
description = "As described: “Transcriptions and audio files of over 600 traditional fiddle tunes from old recordings, festivals, jams, and workshops.” A nicely curated selection of tunes reflecting different regional fiddling cultures. Clean, modern website with fast-loading resources."
author = "John Lamancusa"
url = "https://www.mne.psu.edu/lamancusa/tunes.html"
