title = "Pete Showman's Tunes Page"
description = "A nicely curated selection of old-time tunes, mostly American (or as they are known here). Many are simpler arrangements ideal for learning. MIDI files and some recordings are available. Fast static HTML website."
author = "Pete Showman"
url = "http://www.showman.org/tunes/"
