title = "Australian Traditional Music Tunes Archive"
description = "As described: “a searchable collection of tunes in ABC Music Notation format . . . and associated supporting bio and documentary material.” Audio files for some of the tunes can be located on another part of the site. Pages load slowly from a US East Coast location, likely because data is being transmitted from a server in Australia."
author = "Ray Mulligan and contributors"
url = "https://bushtraditions.wiki/tunes/index.php/Main_Page"
