title = "Roots of Bluegrass Music: Early Country Music"
description = "Historical and biographical information on pre-WWII recording artists, folk-song collectors, and their informants. Includes extensive bibliographic references. (Unfortunately, individual pages on this site load slowly – the content is rendered by a CMS database application that appears to be poorly optimized.)"
author = "Richard L. Matteson, Jr."
url = "http://www.bluegrassmessengers.com/roots.aspx"
