title = "Bluegrass Lyrics"
description = "This collection includes lyrics, music notation, and extensive source notes for traditional ballads and fiddle/banjo tunes, as well as popular standards in Bluegrass and related modern genres. Some comparative analysis of songs/tunes/versions is interspersed. (Unfortunately, individual pages on this site load slowly – the content is rendered by a CMS database application that appears to be poorly optimized.)"
author = "Richard L. Matteson, Jr."
url = "http://www.bluegrassmessengers.com/bluegrass-lyrics.aspx"
