title = "Broadside Ballads Online"
description = "As described: “a digital collection of English printed ballad-sheets from between the 16th and 20th centuries, linked to other resources for the study of the English ballad tradition.”"
author = "Bodleian Libraries (Oxford)"
url = "http://ballads.bodleian.ox.ac.uk/"
